/* tslint:disable */
/* eslint-disable */
/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface IambackofficeRegistrationRequest
 */
export interface IambackofficeRegistrationRequest {
    /**
     * 
     * @type {IambackofficeUserRegistration}
     * @memberof IambackofficeRegistrationRequest
     */
    'registration'?: IambackofficeUserRegistration;
    /**
     * 
     * @type {boolean}
     * @memberof IambackofficeRegistrationRequest
     */
    'sendSetPasswordEmail'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IambackofficeRegistrationRequest
     */
    'skipRegistrationVerification'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IambackofficeRegistrationRequest
     */
    'skipVerification'?: boolean;
    /**
     * 
     * @type {IambackofficeUser}
     * @memberof IambackofficeRegistrationRequest
     */
    'user'?: IambackofficeUser;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeRegistrationRequest
     */
    'tenantId'?: string;
}
