/* tslint:disable */
/* eslint-disable */
/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface IambackofficeCreateGroupRequest
 */
export interface IambackofficeCreateGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof IambackofficeCreateGroupRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeCreateGroupRequest
     */
    'name'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IambackofficeCreateGroupRequest
     */
    'data'?: { [key: string]: string; };
}
