/* tslint:disable */
/* eslint-disable */
/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface IambackofficeLoginRequest
 */
export interface IambackofficeLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof IambackofficeLoginRequest
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeLoginRequest
     */
    'ipAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeLoginRequest
     */
    'loginId'?: string;
    /**
     * 
     * @type {IambackofficeMetaData}
     * @memberof IambackofficeLoginRequest
     */
    'metaData'?: IambackofficeMetaData;
    /**
     * 
     * @type {boolean}
     * @memberof IambackofficeLoginRequest
     */
    'noTokens'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeLoginRequest
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeLoginRequest
     */
    'twoFactorTrustId'?: string;
}
