/* tslint:disable */
/* eslint-disable */
/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface IambackofficeAuthenticatorConfiguration
 */
export interface IambackofficeAuthenticatorConfiguration {
    /**
     * 
     * @type {string}
     * @memberof IambackofficeAuthenticatorConfiguration
     */
    'algorithm'?: string;
    /**
     * 
     * @type {number}
     * @memberof IambackofficeAuthenticatorConfiguration
     */
    'codeLength'?: number;
    /**
     * 
     * @type {number}
     * @memberof IambackofficeAuthenticatorConfiguration
     */
    'timeStep'?: number;
}
