/* tslint:disable */
/* eslint-disable */
/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface IambackofficeUser
 */
export interface IambackofficeUser {
    /**
     * 
     * @type {boolean}
     * @memberof IambackofficeUser
     */
    'active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'birthDate'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IambackofficeUser
     */
    'data'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'fullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'insertInstant'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'lastLoginInstant'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'lastUpdateInstant'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'middleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'mobilePhone'?: string;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'password'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IambackofficeUser
     */
    'passwordChangeRequired'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'passwordLastUpdateInstant'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IambackofficeUser
     */
    'preferredLanguages'?: Array<string>;
    /**
     * 
     * @type {Array<IambackofficeUserRegistration>}
     * @memberof IambackofficeUser
     */
    'registrations'?: Array<IambackofficeUserRegistration>;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'timezone'?: string;
    /**
     * 
     * @type {IambackofficeUserTwoFactorConfiguration}
     * @memberof IambackofficeUser
     */
    'twoFactor'?: IambackofficeUserTwoFactorConfiguration;
    /**
     * 
     * @type {string}
     * @memberof IambackofficeUser
     */
    'username'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IambackofficeUser
     */
    'verified'?: boolean;
}
