/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IambackofficeUser } from '../models/IambackofficeUser';
import { IambackofficeUserRegistration } from '../models/IambackofficeUserRegistration';
import { ProtobufAny } from '../models/ProtobufAny';
import { HttpFile } from '../http/http';

export class IambackofficeRegistrationResponse {
    'tokens'?: ProtobufAny;
    'registration'?: IambackofficeUserRegistration;
    'user'?: IambackofficeUser;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "ProtobufAny",
            "format": ""
        },
        {
            "name": "registration",
            "baseName": "registration",
            "type": "IambackofficeUserRegistration",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IambackofficeUser",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeRegistrationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

