/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IambackofficeUserRegistration } from '../models/IambackofficeUserRegistration';
import { IambackofficeUserTwoFactorConfiguration } from '../models/IambackofficeUserTwoFactorConfiguration';
import { HttpFile } from '../http/http';

export class IambackofficeUser {
    'active'?: boolean;
    'birthDate'?: string;
    'data'?: { [key: string]: string; };
    'email'?: string;
    'firstName'?: string;
    'fullName'?: string;
    'id'?: string;
    'imageUrl'?: string;
    'insertInstant'?: string;
    'lastLoginInstant'?: string;
    'lastName'?: string;
    'lastUpdateInstant'?: string;
    'middleName'?: string;
    'mobilePhone'?: string;
    'password'?: string;
    'passwordChangeRequired'?: boolean;
    'passwordLastUpdateInstant'?: string;
    'preferredLanguages'?: Array<string>;
    'registrations'?: Array<IambackofficeUserRegistration>;
    'timezone'?: string;
    'twoFactor'?: IambackofficeUserTwoFactorConfiguration;
    'username'?: string;
    'verified'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "birthDate",
            "baseName": "birthDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "fullName",
            "baseName": "fullName",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "insertInstant",
            "baseName": "insertInstant",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "lastLoginInstant",
            "baseName": "lastLoginInstant",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastUpdateInstant",
            "baseName": "lastUpdateInstant",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string",
            "format": ""
        },
        {
            "name": "mobilePhone",
            "baseName": "mobilePhone",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "passwordChangeRequired",
            "baseName": "passwordChangeRequired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "passwordLastUpdateInstant",
            "baseName": "passwordLastUpdateInstant",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "preferredLanguages",
            "baseName": "preferredLanguages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "registrations",
            "baseName": "registrations",
            "type": "Array<IambackofficeUserRegistration>",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "twoFactor",
            "baseName": "twoFactor",
            "type": "IambackofficeUserTwoFactorConfiguration",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeUser.attributeTypeMap;
    }

    public constructor() {
    }
}

