/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchGroupsRequestFilters } from '../models/SearchGroupsRequestFilters';
import { HttpFile } from '../http/http';

export class IambackofficeSearchGroupsRequest {
    'tenantId'?: string;
    'filters'?: SearchGroupsRequestFilters;
    'filtersMask'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "SearchGroupsRequestFilters",
            "format": ""
        },
        {
            "name": "filtersMask",
            "baseName": "filtersMask",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeSearchGroupsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

