/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IambackofficeAuthenticatorConfiguration } from '../models/IambackofficeAuthenticatorConfiguration';
import { HttpFile } from '../http/http';

export class IambackofficeTwoFactorMethod {
    'authenticator'?: IambackofficeAuthenticatorConfiguration;
    'email'?: string;
    'id'?: string;
    'method'?: string;
    'mobilePhone'?: string;
    'secret'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "authenticator",
            "baseName": "authenticator",
            "type": "IambackofficeAuthenticatorConfiguration",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string",
            "format": ""
        },
        {
            "name": "mobilePhone",
            "baseName": "mobilePhone",
            "type": "string",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeTwoFactorMethod.attributeTypeMap;
    }

    public constructor() {
    }
}

