/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IambackofficeTwoFactorMethod } from '../models/IambackofficeTwoFactorMethod';
import { IambackofficeUser } from '../models/IambackofficeUser';
import { ProtobufAny } from '../models/ProtobufAny';
import { HttpFile } from '../http/http';

export class IambackofficeLoginResponse {
    'tokens'?: ProtobufAny;
    'user'?: IambackofficeUser;
    'methods'?: Array<IambackofficeTwoFactorMethod>;
    'twoFactorId'?: string;
    'tenantId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "ProtobufAny",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IambackofficeUser",
            "format": ""
        },
        {
            "name": "methods",
            "baseName": "methods",
            "type": "Array<IambackofficeTwoFactorMethod>",
            "format": ""
        },
        {
            "name": "twoFactorId",
            "baseName": "twoFactorId",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeLoginResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

