/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IambackofficeAuthenticatorConfiguration {
    'algorithm'?: string;
    'codeLength'?: number;
    'timeStep'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "algorithm",
            "baseName": "algorithm",
            "type": "string",
            "format": ""
        },
        {
            "name": "codeLength",
            "baseName": "codeLength",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timeStep",
            "baseName": "timeStep",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeAuthenticatorConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

