/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IambackofficeUser } from '../models/IambackofficeUser';
import { IambackofficeUserRegistration } from '../models/IambackofficeUserRegistration';
import { HttpFile } from '../http/http';

export class IambackofficeRegistrationRequest {
    'registration'?: IambackofficeUserRegistration;
    'sendSetPasswordEmail'?: boolean;
    'skipRegistrationVerification'?: boolean;
    'skipVerification'?: boolean;
    'user'?: IambackofficeUser;
    'tenantId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "registration",
            "baseName": "registration",
            "type": "IambackofficeUserRegistration",
            "format": ""
        },
        {
            "name": "sendSetPasswordEmail",
            "baseName": "sendSetPasswordEmail",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "skipRegistrationVerification",
            "baseName": "skipRegistrationVerification",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "skipVerification",
            "baseName": "skipVerification",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IambackofficeUser",
            "format": ""
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeRegistrationRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

