/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IambackofficeTwoFactorMethod } from '../models/IambackofficeTwoFactorMethod';
import { HttpFile } from '../http/http';

export class IambackofficeUserTwoFactorConfiguration {
    'methods'?: Array<IambackofficeTwoFactorMethod>;
    'recoveryCodes'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "methods",
            "baseName": "methods",
            "type": "Array<IambackofficeTwoFactorMethod>",
            "format": ""
        },
        {
            "name": "recoveryCodes",
            "baseName": "recoveryCodes",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeUserTwoFactorConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

