/**
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProtobufAny } from '../models/ProtobufAny';
import { HttpFile } from '../http/http';

export class IambackofficeLogoutRequest {
    'global'?: boolean;
    'tokens'?: ProtobufAny;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "global",
            "baseName": "global",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "ProtobufAny",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IambackofficeLogoutRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

